# Generated by Django 5.1.6 on 2025-02-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_review_star"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="director",
            options={"verbose_name": "Директор", "verbose_name_plural": "Директоры"},
        ),
        migrations.RemoveField(
            model_name="review",
            name="star",
        ),
    ]
