# Generated by Django 5.1.6 on 2025-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0003_alter_director_options_remove_review_star"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
